# Generated by Django 5.1.6 on 2025-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='entity_type',
            field=models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('activity', 'Activity')], default='destination', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_photos/'),
        ),
    ]
